const express=require('express')
const app = express()
require('dotenv').config()
const bodyParser=require('body-parser')
const connectDb=require('./db/conection')
const userRouter=require('./Routes/router')
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended:false}))
app.use(express.json())
app.use(userRouter)
app.listen(8000,()=>{console.log(`Server Connected on Port ${process.env.PORT}`);})