const express=require('express')
const app = express()
require('dotenv').config()
const cors=require('cors')
const bodyParser=require('body-parser')
const connectDb=require('./db/conection')
const userRouter=require('./Routes/router')
const swaggerUI = require('swagger-ui-express')
const options =require('./swaggerdocs')
const swaggerJsDoc = require('swagger-jsdoc')
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended:false}))
app.use(express.json())
app.use(cors("http://localhost/8000/alluser"))
const swaggerDoc=swaggerJsDoc(options)
app.use('/swaggerapi',swaggerUI.serve,swaggerUI.setup(swaggerDoc))
app.use(userRouter)
app.listen(8000,()=>{console.log(`Server Connected on Port ${process.env.PORT}`)})